#!/usr/bin/env bash

url=$( jq -r '.url' data.json )
response=$( curl -s $url )
type=$( echo $response | jq '.types[].type.name')
type=$( echo $type | tr -d '"')
# capitlize the first letter
type=$( echo $type | sed 's/./\U&/' )
weight=$( echo $response | jq '.weight')
height=$( echo $response | jq '.height')
echo "Pikachu is of type ${type}, weighs ${weight}, and is 0.${height}m tall."
